mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: vip.linfeng.mcweb.pojo
spring:
  datasource:
    username: mc
    password: mc
    url: jdbc:mysql://localhost:3306/mc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
shop:
    # 购买最大健康值的初始值
    max-health-money: 20000.00
    # 可购买到的最大健康值
    max-health-to-max: 40
    # 每次购买后再次购买一点血量所需增加的金额（一颗心是两点血）
    max-health-next-add-money: 15000.00
